### ISSUE TITLE
Not able to deploy locally

### ISSUE THREAD

**Issue by kkbandaru** [Azure/azure-iot-pcs-remote-monitoring-dotnet#104] opened 2018-05-29 14:28 UTC
When I try to deploy local I am getting error in logs, please let me know which branch to pick

Error 1:

devicesimulation_1  | [ERROR][2018-05-29 14:26:23.323][WebService.4c0c3057-89d4-4405-90f6-6d4962319b4d][Simulation:RunAsync] Failure reading and starting simulation from storage., {"e":{"ExceptionFullName":"Microsoft.Azure.IoTSolutions.DeviceSimulation.Services.Exceptions.ExternalDependencyException","ExceptionMessage":"An unexpected error happened while using an external dependency.","StackTrace":"   at Microsoft.Azure.IoTSolutions.DeviceSimulation.Services.StorageAdapter.StorageAdapterClient.ThrowIfError(IHttpResponse response, String collectionId, String key) in /opt/vsts/work/1/s/Services/StorageAdapter/StorageAdapterClient.cs:line 172\n   at Microsoft.Azure.IoTSolutions.DeviceSimulation.Services.StorageAdapter.StorageAdapterClient.<GetAllAsync>d__7.MoveNext() in /opt/vsts/work/1/s/Services/StorageAdapter/StorageAdapterClient.cs:line 84\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n   at Microsoft.Azure.IoTSolutions.DeviceSimulation.Services.Simulations.<GetListAsync>d__9.MoveNext() in /opt/vsts/work/1/s/Services/Simulations.cs:line 85\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n   at Microsoft.Azure.IoTSolutions.DeviceSimulation.SimulationAgent.Simulation.<RunAsync>d__7.MoveNext() in /opt/vsts/work/1/s/SimulationAgent/Simulation.cs:line 50","Source":"Microsoft.Azure.IoTSolutions.DeviceSimulation.Services","Data":{},"InnerException":{"ExceptionFullName":"System.Net.Http.HttpRequestException","ExceptionMessage":"Storage request error: status code 0","StackTrace":null,"Source":null,"Data":{},"InnerException":null}}}

Error 2:
[ERROR][2018-05-29 14:20:10.045][WebService.3c7c744e-0e9e-4b0d-b9ab-29d1d7833049][Agent:CreateMessagesTableAsync] Messages storage setup failed. Unable to create messages table., {"e":{"ExceptionFullName":"Microsoft.Azure.IoTSolutions.AsaManager.Services.Exceptions.ExternalDependencyException","ExceptionMessage":"Error while creating the output storage","StackTrace":"   at Microsoft.Azure.IoTSolutions.AsaManager.Services.Storage.AsaStorage.<SetupOutputStorageAsync>d__7.MoveNext() in /opt/vsts/work/1/s/Services/Storage/AsaStorage.cs:line 64\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n   at SetupAgent.Agent.<CreateMessagesTableAsync>d__8.MoveNext() in /opt/vsts/work/1/s/SetupAgent/Agent.cs:line 67","Source":"Microsoft.Azure.IoTSolutions.AsaManager.Services","Data":{},"InnerException":{"ExceptionFullName":"Microsoft.Azure.IoTSolutions.AsaManager.Services.Exceptions.InvalidConfigurationException","ExceptionMessage":"Invalid connection string for Cosmos DB (format: '$^AccountEndpoint=(?<endpoint>.*);AccountKey=(?<key>.*);$')","StackTrace":"   at Microsoft.Azure.IoTSolutions.AsaManager.Services.Storage.CosmosDbSql.ParseConnectionString(Uri& uri, String& authKey) in /opt/vsts/work/1/s/Services/Storage/CosmosDbSql.cs:line 84\n   at Microsoft.Azure.IoTSolutions.AsaManager.Services.Storage.CosmosDbSql.<CreateDatabaseAndCollectionsIfNotExistAsync>d__11.MoveNext() in /opt/vsts/work/1/s/Services/Storage/CosmosDbSql.cs:line 69\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n   at Microsoft.Azure.IoTSolutions.AsaManager.Services.Storage.AsaStorage.<SetupOutputStorageAsync>d__7.MoveNext() in /opt/vsts/work/1/s/Services/Storage/AsaStorage.cs:line 57","Source":"Microsoft.Azure.IoTSolutions.AsaManager.Services","Data":{},"InnerException":null}}}

# Screenshot 

# Steps to reproduce 
1. [First step]
2. [Second step]
3. [and so on...]

# Expected behavior 
...

# Current behavior 
...

# Known workarounds 
...

# Possible solution 
...

# Context and Environment
* Operating System: ...
* GitHub branch: ...
* .NET Runtime: ...

**Comment by prabhu66** [comment] 2018-06-01 09:11
can u please provide me the screenshot error of the UI(http://localhost:8080/dashboard) @kkbandaru .

**Comment by zhang-hua** [comment] 2018-06-12 17:08
@kkbandaru : can you check if the CosmosDB connection string format is valid for the environment variable `PCS_TELEMETRY_DOCUMENTDB_CONNSTRING`? Make sure it is similar to "AccountEndpoint=https://xxxxxxxx.documents.azure.com:443/;AccountKey=xxxxxxxxx;".  The exception message is complaining the format of this setting.

**Comment by ppathan** [comment] 2018-07-27 05:12
@kkbandaru Can you please comment if the issue is fixed otherwise we will close it.

**Closed** 2018-08-22 18:26 UTC
Labels: Triaged
