### ISSUE TITLE
Error: Oops, we were not able to find the service on dashboard after 200 simulated deivces added (standard RM)

### ISSUE THREAD

**Issue by sakimsft** [Azure/azure-iot-pcs-remote-monitoring-dotnet#145] opened 2018-11-19 18:58 UTC
# Type of issue 
- [x] Bug
- [ ] New feature
- [ ] Improvement

# Description 
This issue is originally reported from the customer. 
(Oleksandr Shkabura <Oleksandr.Shkabura@infopulse.com>)

Create standard RM via PCS CLI and then add 200 simulated devices.
Dashboard shows "Error: Oops, we were not able to find the service." due to below error.

HTTP404: NOT FOUND - The server has not found anything matching the requested URI (Uniform Resource Identifier).
(XHR)GET - https://saki-standard-1.azurewebsites.net/telemetry/v1/alarms?devices=chiller-01.46%2Cengine-01.42%2Cengine-01.18%2Cdelivery-truck-01.19%2Cdelivery-truck-01.9%2Cengine-01.47%2Cengine-01.27%2Cdelivery-truck-01.37%2Cchiller-01.32%2Cdelivery-truck-01.42%2Cchiller-01.44%2Cengine-01.8%2Cengine-01.26%2Cengine-01.6%2Cengine-01.7%2Cchiller-01.4%2Cengine-01.9%2Cdelivery-truck-01.13%2Cchiller-01.3%2Cdelivery-truck-02.0%2Cengine-01.44%2Cchiller-01.37%2Cdelivery-truck-01.4%2Cchiller-01.39%2Cdelivery-truck-01.35%2Cengine-01.12%2Cchiller-01.11%2Cchiller-01.16%2Cengine-01.22%2Cengine-01.34%2Cdelivery-truck-01.25%2Cdelivery-truck-01.33%2Cengine-01.33%2Cdelivery-truck-01.2%2Cdelivery-truck-01.23%2Cchiller-01.36%2Cprototype-02.0%2Cchiller-01.12%2Cchiller-01.23%2Cdelivery-truck-01.8%2Cchiller-01.30%2Cchiller-01.20%2Cchiller-01.27%2Cchiller-01.22%2Cchiller-01.7%2Cdelivery-truck-01.44%2Cengine-01.49%2Cdelivery-truck-

Note:
1. Confirmed that telemetry service was up and running.
2. Could be related to the issue that URL is too long (see the above request URL is not fully completed format)
3. There was no authorization error

# Screenshot 
![image](https://user-images.githubusercontent.com/43823418/48728813-e0ba9900-ebea-11e8-874b-4d411f0ccefc.png)

# Steps to reproduce 
1. Create standard RM via PCS CLI
2. Add 200 simulated devices

# Expected behavior 
Dashboard displays 200 devices without an error.

# Current behavior 
Dashboard displays "Error: Oops, we were not able to find the service."

# Known workarounds 
...

# Possible solution 
...

# Context and Environment
* Operating System: ...
* GitHub branch: ...
* .NET Runtime: ...

**Comment by ppathan** [comment] 2018-11-19 19:57
Duplicate of #108. Closing this and we are already working on the original bug.

**Closed by ppathan** 2018-11-19 19:57 UTC
Labels: duplicate
